name: GPT-FETCH App Run

on: 
    pull_request:
        branches: 
            - master

jobs:
    run:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src
        
        strategy:
            matrix:
                python-version: [3.11]

        env:
            MODE: "dev"

        steps: 
            - uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r ../requirements.txt

            - name: Run
              run: |
                  python main.py