name: GPT-FETCH App Run

on: 
    workflow_dispatch:
        inputs:
            mode:
                description: 'Mode'
                required: true
                default: 'dev'

jobs:
    run:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src
        
        strategy:
            matrix:
                python-version: [3.11]

        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
            MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
            MONGO_DB: ${{ secrets.MONGO_DB }}
            CONVERSATION_LIST_COLLECTION: ${{ secrets.CONVERSATION_LIST_COLLECTION }}
            CONVERSATIONS_COLLECTION: ${{ secrets.CONVERSATIONS_COLLECTION }}

        steps: 
            - uses: actions/checkout@v3

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.9.0

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r ../requirements.txt

            - name: Run
              run: |
                  python main.py