name: GPT-FETCH App Run

on: 
    workflow_dispatch:
        inputs:
            mode:
                description: 'Mode'
                required: true
                default: 'dev'

jobs:
    pre-commit:
        name: pre-commit
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v3
          - uses: pre-commit/action@v3.0.0
            with:
              extra_args: --all-files --hook-stage=manual

    build:
        runs-on: ubuntu-latest
        # defaults:
        #     run:
        #         working-directory: ./src
        strategy:
            matrix:
                os: [ubuntu-20.04]
                python-version: ["3.10"]

        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
            MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
            MONGO_DB: ${{ secrets.MONGO_DB }}
            CONVERSATION_LIST_COLLECTION: ${{ secrets.CONVERSATION_LIST_COLLECTION }}
            CONVERSATIONS_COLLECTION: ${{ secrets.CONVERSATIONS_COLLECTION }}

        steps: 
            - uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'pip'
                  cache-dependency-path: './src/main.py'
            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                mongodb-version: 5.3.2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r ./requirements.txt
            - name: Run
              run: |
                  python main.py

